---
- name: Ping Ansible Hosts
  hosts:         deploy1,localhost1,pihole1,pihole2
  remote_user:   ansible
  gather_facts:  false

  tasks:
    - name: ping ansible hosts
      ping:
      tags:
        - ping
